# -*- coding: utf-8 -*-
"""precollation-test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjx2rB6MnBv8GwajkU8StgPN0jaaRIiC
"""

import pickle
import pathlib
import shutil
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy.stats import spearmanr, kendalltau
import os
import torch

from utils import copy_figure, save_fig
from core.timing import timeit, TimerContext, get_device
from core.pooling import (
    extract_features, extract_features_batch, PHYSICAL_SCALES_MM,
)
from core.scoring import clutter_score, clutter_score_batch
from core.percolation import (
    PC_THEORY, largest_cluster_fraction, spans_image,
    first_derivative, second_derivative,
    find_inflection, find_peak_derivative,
)

IMAGE_SIZE = 700, 600

w_density:       float = 0.4
w_irregularity:  float = 0.35
w_fragmentation: float = 0.25


# ──────────────────────────────────────────────
# EXPERIMENT: single run
# ──────────────────────────────────────────────

def generate_batch_images(seed, ps, h, w):
    rng = np.random.default_rng(seed)
    images = []
    images = rng.random((len(ps), h, w))
    images = (images < ps[:, np.newaxis, np.newaxis]).astype(np.float32)
    return images

def single_run_batch(ps: np.ndarray,
               h: int = 700, w: int = 600,
               mm_per_pixel: float = 1.0,
               seed: int = 42,
               device: torch.device = get_device()) -> dict:
    """
    Generate one Bernoulli image per p value, compute all metrics.
    Feature extraction runs as a single batched forward pass on `device`.
    lcf and spanning remain per-image on CPU (scipy cc_label dependency).
    Returns dict of arrays indexed by ps.
    """

    # ── generate all images up front ─────────────────────────────────────────
    imgs_np = generate_batch_images(seed, ps, h, w) # (N, H, W)

    # ── batch feature extraction on device ───────────────────────────────────
    imgs_t  = torch.from_numpy(imgs_np).to(device)          # (N, H, W)
    with TimerContext() as t_batch:
        feats   = extract_features_batch(imgs_t, mm_per_pixel)   # (N, 4*S)
        scores  = clutter_score_batch(feats).cpu().numpy()       # (N,)

    # ── per-image physical metrics (CPU, scipy) ───────────────────────────────
    lcf      = np.array([largest_cluster_fraction(img) for img in imgs_np])
    spanning = np.array([float(spans_image(img))        for img in imgs_np])

    return {
        "scores":   scores,
        "lcf":      lcf,
        "spanning": spanning,
        "time_sec": t_batch.elapsed / len(ps),
    }

def single_run(ps: np.ndarray,
               h: int = 700, w: int = 600,
               mm_per_pixel: float = 1.0,
               seed: int = 42) -> dict:
    """
    Generate one Bernoulli image per p value, compute all metrics.
    Returns dict of arrays indexed by ps.
    """
    rng = np.random.default_rng(seed)
    scores, lcf, spanning = [], [], []
    times = []
    for p in ps:
        img = (rng.random((h, w)) < p).astype(np.float32)
        with TimerContext() as t:
            f   = extract_features(img, mm_per_pixel)
            scores.append(clutter_score(f))
            times.append(t.elapsed)
        lcf.append(largest_cluster_fraction(img))
        spanning.append(float(spans_image(img)))

    return {
        "scores":   np.array(scores),
        "lcf":      np.array(lcf),
        "spanning": np.array(spanning),
        "time_sec": np.mean(times),
    }


# ──────────────────────────────────────────────
# EXPERIMENT: multi-seed robustness
# ──────────────────────────────────────────────

@timeit
def multi_seed_run(ps: np.ndarray,
                   n_seeds: int = 20,
                   h: int = 700, w: int = 600,
                   mm_per_pixel: float = 1.0) -> dict:
    """
    Run experiment over n_seeds random seeds.
    Returns mean ± std across seeds for each p value.
    """
    all_scores   = []
    all_lcf      = []
    all_spanning = []
    inflections  = []
    peak_grads   = []
    all_times = []
    h, w = IMAGE_SIZE
    print(f"  Running {n_seeds} seeds × {len(ps)} occupancy values …")
    for seed in range(n_seeds):
        # r = single_run(ps, h, w, mm_per_pixel, seed=seed)
        r = single_run_batch(ps, h, w, mm_per_pixel, seed=seed)


        all_scores.append(r["scores"])
        all_lcf.append(r["lcf"])
        all_spanning.append(r["spanning"])
        all_times.append(r["time_sec"])
        inflections.append(find_inflection(r["scores"], ps))
        peak_grads.append(find_peak_derivative(r["scores"], ps))
        if (seed + 1) % 5 == 0:
            print(f"    seed {seed+1}/{n_seeds} done")

    scores_arr = np.array(all_scores)   # (n_seeds, n_ps)
    lcf_arr    = np.array(all_lcf)
    span_arr   = np.array(all_spanning)
    times_arr  = np.array(all_times)
    return {
        "scores_mean":    scores_arr.mean(axis=0),
        "scores_std":     scores_arr.std(axis=0),
        "lcf_mean":       lcf_arr.mean(axis=0),
        "lcf_std":        lcf_arr.std(axis=0),
        "spanning_mean":  span_arr.mean(axis=0),
        "time_sec":       np.mean(times_arr),
        "inflections":    np.array(inflections),
        "peak_grads":     np.array(peak_grads),
    }


# ──────────────────────────────────────────────
# MAIN ANALYSIS + PLOTS
# ──────────────────────────────────────────────

def run_percolation_validation(save_dir: str = "results",
                               mm_per_pixel: float = 1.0,
                               n_seeds: int = 20,
                               n_ps: int = 60,
                               image_size: tuple = (700, 600)):
    h, w = image_size
    os.makedirs(save_dir, exist_ok=True)

    # Dense p sweep focused around p_c
    ps = np.linspace(0.30, 0.80, n_ps)
    # create an unique key for this experiment configuration
    exp_key = f"{h}x{w}_s{n_seeds}_p{n_ps}_mm{mm_per_pixel}"
    experiment_file = os.path.join(save_dir, f"percolation_{exp_key}.pkl")
    
    print("=" * 60)
    print("PERCOLATION THRESHOLD VALIDATION")
    print(f"  p range     : {ps[0]:.2f} → {ps[-1]:.2f}  ({n_ps} steps)")
    print(f"  pc theory  : {PC_THEORY}")
    print(f"  image size  : {h}x{w}")
    print(f"  mm/px       : {mm_per_pixel}")
    print(f"  seeds       : {n_seeds}")
    print(f"weights {w_density, w_irregularity, w_fragmentation}")
    print("=" * 60)

    # ── compute ───────────────────────────────
    results = None
    if os.path.exists(experiment_file):
        # load precomputed results if available (speeds up iterative development and plotting)
        try:
            with open(experiment_file, 'rb') as f:
                results = pickle.load(f)
                print(f"Loaded precomputed results from \n\t'{experiment_file}'")
        except Exception:
            results = None
    if results is None:
        print(f"Device type: {get_device()}")
        results = multi_seed_run(ps, n_seeds=n_seeds, mm_per_pixel=mm_per_pixel, h=h, w=w)
        # save results for future reuse
        with open(experiment_file, 'wb') as f:
            pickle.dump(results, f)

    scores_mean = results["scores_mean"]
    scores_std  = results["scores_std"]
    lcf_mean    = results["lcf_mean"]
    spanning    = results["spanning_mean"]
    inflections = results["inflections"]
    peak_grads  = results["peak_grads"]

    # ── derivatives (on mean curve) ───────────
    d1 = first_derivative(scores_mean, ps)
    d2 = second_derivative(scores_mean, ps)

    inflection_p  = find_inflection(scores_mean, ps)
    peak_grad_p   = find_peak_derivative(scores_mean, ps)

    # ── print numerical summary ───────────────
    print(f"\nGradient Analysis Results")
    print(f"  Peak of dC/dp (max gradient)        : p = {peak_grad_p:.4f}")
    print(f"  Inflection point (d²C/dp²=0)        : p = {inflection_p:.4f}")
    print(f"  Theoretical pc                     : {PC_THEORY:.4f}")
    error = abs(inflection_p - PC_THEORY)
    print(f"  Error (inflection vs theory)        : {error:.4f}")
    error_p = abs(error/PC_THEORY)*100
    print(f"  Error% (inflection vs theory)        : {error_p:.4f}")
    print(f"\nMulti-seed Robustness")
    print(f"  Mean detected inflection ± std      : "
          f"{inflections.mean():.4f} ± {inflections.std():.4f}")
    print(f"  Mean peak gradient p ± std          : "
          f"{peak_grads.mean():.4f} ± {peak_grads.std():.4f}")

    # Spearman between score and LCF (physical GT)
    rho, pval = spearmanr(scores_mean, lcf_mean)
    print(f"\n  Spearman ρ (clutter score vs LCF)   : {rho:.4f}  (p={pval:.2e})")
    tau, p_tau = kendalltau(scores_mean, lcf_mean)
    print(f"  Kendall τ (clutter score vs LCF)   : {tau:.4f}  (p={p_tau:.2e})")

    # ################################################################################
    
    if True:
        if True:
            # ── FIGURE 1: main 4-panel percolation plot ──
            fig = plt.figure(figsize=(20, 10))
            fig.suptitle("Percolation Threshold Validation\n"
                        "Pooling-Based Clutter Score vs Bernoulli Occupancy Field",
                        fontsize=14, fontweight="bold")
            gs = gridspec.GridSpec(2, 3, figure=fig, hspace=0.42, wspace=0.32)

            # Panel 1: score curve with CI
            ax1 = fig.add_subplot(gs[0, 0])
            # ax1.fill_between(ps,
            #                 scores_mean - scores_std,
            #                 scores_mean + scores_std,
            #                 alpha=0.25, color="lightseagreen", label="± std")
            ax1.axvline(inflections.mean(), color="lightseagreen", lw=1.5, label=f"mean score={inflections.mean():.4f}")
            ax1.axvline(PC_THEORY,    color="red",    lw=1.5, ls="--", label=f"pc theory = {PC_THEORY}")
            ax1.axvline(inflection_p, color="black", lw=1.5, ls=":",
                        label=f"inflection p̂c = {inflection_p:.4f}")
            ax1.set_xlim(0.59, 0.596)
            ax1.set_xlabel("Occupancy p")
            ax1.set_ylabel("Clutter score")
            ax1.set_title(f"A: Score vs occupancy\n({n_ps} occupancy values,\n{n_seeds} seeds)")
            ax1.legend(fontsize=8)
            ax1.grid(True, alpha=0.3)

            # Panel 2: first derivative
            ax2 = fig.add_subplot(gs[0, 1])
            ax2.plot(ps, d1, color="cornflowerblue", lw=2.5, label="dC/dp")
            ax2.fill_between(ps, 0, d1,
                            where=(d1 > 0), alpha=0.2, color="cornflowerblue")
            ax2.axvline(PC_THEORY,   color="red",    lw=1.5, ls="--", label=f"p_c = {PC_THEORY}")
            ax2.axvline(peak_grad_p, color="purple", lw=1.5, ls=":",
                        label=f"peak = {peak_grad_p:.3f}")
            ax2.axhline(0, color="gray", lw=0.8)
            ax2.set_xlabel("Occupancy p")
            ax2.set_ylabel("dC/dp")
            ax2.set_title("B: First derivative\n(peak = steepest transition)")
            ax2.legend(fontsize=8)
            ax2.grid(True, alpha=0.3)

            # Panel 3: second derivative
            ax3 = fig.add_subplot(gs[1, 0])
            ax3.plot(ps, d2, color="red", lw=2.5, label="d²C/dp²")
            ax3.fill_between(ps, 0, d2,
                            where=(d2 > 0), alpha=0.15, color="red")
            ax3.fill_between(ps, 0, d2,
                            where=(d2 < 0), alpha=0.15, color="orange")
            ax3.axvline(PC_THEORY,    color="red",    lw=1.5, ls="--", label=f"p_c = {PC_THEORY}")
            ax3.axvline(inflection_p, color="black", lw=1.5, ls=":",
                        label=f"zero-cross = {inflection_p:.3f}")
            ax3.axhline(0, color="gray", lw=1.5, label="zero")
            ax3.set_xlabel("Occupancy p")
            ax3.set_ylabel("d²C/dp²")
            ax3.set_title("C: Second derivative\n(zero-crossing = inflection point p̂c)")
            ax3.legend(fontsize=8)
            ax3.grid(True, alpha=0.3)

            # Panel 4: physical GT overlay
            ax4 = fig.add_subplot(gs[1, 1])
            ax4_twin = ax4.twinx()
            l1, = ax4.plot(ps, scores_mean, color="lightseagreen", lw=2.5,
                        label="clutter score")
            l2, = ax4_twin.plot(ps, lcf_mean, color="orange", lw=2,
                                ls="--", label="largest cluster fraction")
            l3, = ax4_twin.plot(ps, spanning, color="red", lw=1.5,
                                ls=":", label="spanning probability")
            ax4.axvline(PC_THEORY, color="red", lw=1.5, ls="--")
            ax4.set_xlabel("Occupancy p")
            ax4.set_ylabel("Clutter score", color="lightseagreen")
            ax4_twin.set_ylabel("Physical GT (fraction)", color="orange")
            ax4.set_title(f"D: Score vs physical GT\nSpearman ρ={rho:.3f}\nKendall τ={tau:.4f}")

            lines = [l1, l2, l3]
            ax4.legend(lines, [l.get_label() for l in lines], fontsize=8, loc="upper left")
            ax4.grid(True, alpha=0.3)
            
            # ── Panel E: multi-seed distribution ────
            ax = fig.add_subplot(gs[0, 2])
            ax.hist(inflections, bins=15, color="lightseagreen", edgecolor="white",
                    alpha=0.85, label=f"n={n_seeds} seeds")
            ax.axvline(PC_THEORY,         color="red",    lw=2, ls="--",
                    label=f"p_c theory = {PC_THEORY:.4f}")
            ax.axvline(inflections.mean(), color="orange", lw=2,
                    label=f"mean = {inflections.mean():.4f} ± {inflections.std():.4f}")
            ax.set_xlabel("Detected inflection point p̂c")
            ax.set_ylabel("Count")
            ax.set_title("E1: Distribution of inflection points\nacross random seeds")
            ax.legend(fontsize=9)
            ax.grid(True, alpha=0.3)

            ax = fig.add_subplot(gs[1, 2])
            ax.hist(peak_grads, bins=15, color="cornflowerblue", edgecolor="white",
                    alpha=0.85, label=f"n={n_seeds} seeds")
            ax.axvline(PC_THEORY,          color="red",    lw=2, ls="--",
                    label=f"pc theory = {PC_THEORY:.4f}")
            ax.axvline(peak_grads.mean(),  color="purple", lw=2,
                    label=f"mean = {peak_grads.mean():.4f} ± {peak_grads.std():.4f}")
            ax.set_xlabel("p at peak dC/dp")
            ax.set_ylabel("Count")
            ax.set_title("E2: Distribution of peak gradient\nacross random seeds")
            ax.legend(fontsize=9)
            ax.grid(True, alpha=0.3)

            path1 = os.path.join(save_dir, "figure1_percolation_main.tiff")
            save_fig(fig, path1, bw=False)
            plt.close(fig)
            if exp_key == "700x600_s80_p100_mm1.0":
                copy_figure(path1, "figure 5.3.tiff")
            print(f"\n  → Figure all percolation: {path1}")

    # ################################################################################
    
    # ── print publication-ready caption ──────
    print("\n" + "=" * 60)
    print("PUBLICATION SUMMARY")
    print("=" * 60)
    print(f"""
    Figure caption (draft):
    \"The pooling-based clutter score exhibits a measurable
    phase transition consistent with 2D site percolation theory.
    The inflection point of the score curve, detected via
    zero-crossing of d²C/dp², occurs at p = {inflection_p:.3f}
    (theoretical p_c = {PC_THEORY}; error = {abs(inflection_p-PC_THEORY):.4f}).
    The peak of dC/dp at p = {peak_grad_p:.3f} marks the steepest
    rate of clutter increase. Results are stable across {n_seeds}
    random seeds (inflection: {inflections.mean():.3f} ± {inflections.std():.3f}).
    Spearman ρ between score and largest-cluster fraction = {rho:.3f}.
    Kendall τ between score and largest-cluster fraction = {tau:.3f}.
    Average processing time per image: {results['time_sec']*1000:.2f} ms.
    \"
    """)

    return {
        "Inflection point (p̂c=d²C/dp²) ":     round(float(inflection_p), 4),
        "Error (Δpc=|p̂c-pc|)":     round(float((error)), 4),
        "Error% (Δpc/pc*100)":     round(float(error_p), 4),
        "Peak gradient (dC/dp)":      round(float(peak_grad_p), 4),
        # "inflections_dist": inflections,
        # "peak_grads_dist":  peak_grads,
        "spearman ρ largest-cluster fraction": round(float(rho), 4),
        "spearman ρ p-val": round(float(pval), 4),
        "kendall τ largest-cluster fraction": round(float(tau), 4),
        "kendall τ p-val": round(float(p_tau), 4),
        "time_millisec": round(float(results['time_sec']) * 1000, 2),
    }


# ──────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────

if __name__ == "__main__":
    experiments = [
        # {
        #     "image_size": (700, 600),
        #     "n_seeds": 20,
        #     "n_ps": 80,
        # },
        #         {
        #     "image_size": (700, 600),
        #     "n_seeds": 100,
        #     "n_ps": 80,
        # },
        { # BASE LINE
            "image_size": (700, 600),
            "n_seeds": 80,
            "n_ps": 100,
        },
        # 1024 x 1024
        {
            "image_size": (1024, 1024),
            "n_seeds": 100,
            "n_ps": 100,
        },
        # 2048 x 2048  
        {
            "image_size": (2048, 2048),
            "n_seeds": 150,
            "n_ps": 100,
        },
    ]
    import pandas as pd
    results_list = []
    for exp in experiments:
        save_dir = pathlib.Path(__file__).parent / "results" / f"{exp['image_size']}|{exp['n_seeds']}|{exp['n_ps']}"
        os.makedirs(save_dir, exist_ok=True)
        results = run_percolation_validation(
                save_dir=save_dir,
                mm_per_pixel=1.0,   # change to your sensor resolution
                n_seeds=exp["n_seeds"],         # increase to 50+ for paper-quality robustness
                n_ps=exp["n_ps"],           # increase to 100 for smoother derivative curves
                image_size=exp["image_size"]         # matches original image size in clutter_validation.py
        )
        results['image_size'] = exp["image_size"]
        results['n_ps'] = exp["n_ps"]
        results['n_seeds'] = exp["n_seeds"]
        results_list.append(results)
        # break
    if len(results_list) >= 3:
        df = pd.DataFrame(results_list)
        df.to_csv(pathlib.Path(__file__).parent / "results" / "percolation_summary.csv", index=False)
        print(df.head())
        print("\nAll experiments completed. Summary saved to 'results/percolation_summary.csv'")
